# -*- coding: utf-8 -*-
"""market_efficiency_study.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MmRxS8L1pEm7v68rjKcNmRPI6MsRXqnk
"""

import pandas as pd
import sqlite3

# 1. Dados estruturados com métricas de Alpha (Retorno acima do esperado)
data = {
    'Ticker': ['AAPL', 'MSFT', 'GOOGL', 'AMZN', 'META', 'TSLA', 'JPM'],
    'Sector': ['Tech', 'Tech', 'Tech', 'Retail', 'Tech', 'Auto', 'Finance'],
    'Public_News_Impact': [1.01, 1.00, 0.99, 1.05, 0.97, 1.15, 1.01],
    'Alpha_Generated': [0.005, 0.001, -0.002, 0.04, -0.01, 0.12, 0.002]
}

df = pd.DataFrame(data)

# 2. Lógica de Categorização de Eficiência
# Quanto menor o Alpha absoluto, mais eficiente é o mercado (escala de 0.0 a 1.0)
def categorize_efficiency(alpha):
    abs_alpha = abs(alpha)
    if abs_alpha <= 0.01:
        return "1.0 - Altamente Eficiente (Semi-Strong)"
    elif abs_alpha <= 0.05:
        return "0.5 - Moderadamente Eficiente"
    else:
        return "0.1 - Ineficiente (Oportunidade de Arbitragem)"

df['Efficiency_Score'] = df['Alpha_Generated'].apply(categorize_efficiency)

# 3. SQL: Salvando e Consultando
conn = sqlite3.connect('market_research.db')
df.to_sql('efficiency_test', conn, if_exists='replace', index=False)

# Query para ver o resumo por setor
query = """
SELECT Sector, Ticker, Alpha_Generated, Efficiency_Score
FROM efficiency_test
ORDER BY Sector
"""
final_report = pd.read_sql(query, conn)

print("--- RELATÓRIO TÉCNICO DE EFICIÊNCIA DE MERCADO ---")
print(final_report)

conn.close()